/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A registry connector with its connection state for an org/employee.
 */
export interface ConnectorStatus {
  slug: string;
  name: string;
  description: string;
  auth_type: string;
  docs_url?: string;
  is_connected?: boolean;
  connection_count?: number;
}
