/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { CreateEmployeeRequestRole } from "./createEmployeeRequestRole";
import type { CreateEmployeeRequestPersonality } from "./createEmployeeRequestPersonality";
import type { CreateEmployeeRequestSpecialization } from "./createEmployeeRequestSpecialization";
import type { CreateEmployeeRequestDuties } from "./createEmployeeRequestDuties";
import type { CreateEmployeeRequestMemoryPolicy } from "./createEmployeeRequestMemoryPolicy";

export interface CreateEmployeeRequest {
  name: string;
  /**
   * One of: legal-compliance, support, hr, general
   * @pattern ^(legal-compliance|support|hr|general)$
   */
  employee_type: string;
  role?: CreateEmployeeRequestRole;
  personality?: CreateEmployeeRequestPersonality;
  specialization?: CreateEmployeeRequestSpecialization;
  duties?: CreateEmployeeRequestDuties;
  memory_policy?: CreateEmployeeRequestMemoryPolicy;
}
