/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeResponseEmployeeType } from "./employeeResponseEmployeeType";
import type { EmployeeResponseRole } from "./employeeResponseRole";
import type { EmployeeResponsePersonality } from "./employeeResponsePersonality";
import type { EmployeeResponseSpecialization } from "./employeeResponseSpecialization";
import type { EmployeeResponseDuties } from "./employeeResponseDuties";
import type { EmployeeResponseMemoryPolicy } from "./employeeResponseMemoryPolicy";
import type { EmployeeResponseMcpConnections } from "./employeeResponseMcpConnections";
import type { EmployeeResponseCogneeUserId } from "./employeeResponseCogneeUserId";
import type { EmployeeResponseCogneeDatasetName } from "./employeeResponseCogneeDatasetName";
import type { ChannelAssignmentResponse } from "./channelAssignmentResponse";
import type { EmployeeResponseUpdatedAt } from "./employeeResponseUpdatedAt";

export interface EmployeeResponse {
  id: string;
  org_id: string;
  name: string;
  employee_type?: EmployeeResponseEmployeeType;
  role?: EmployeeResponseRole;
  personality?: EmployeeResponsePersonality;
  specialization?: EmployeeResponseSpecialization;
  duties?: EmployeeResponseDuties;
  memory_policy?: EmployeeResponseMemoryPolicy;
  mcp_connections?: EmployeeResponseMcpConnections;
  status: string;
  has_discord_token: boolean;
  has_slack_token: boolean;
  has_slack_slot?: boolean;
  slack_team_name?: string | null;
  cognee_user_id?: EmployeeResponseCogneeUserId;
  cognee_dataset_name?: EmployeeResponseCogneeDatasetName;
  channel_assignments?: ChannelAssignmentResponse[];
  created_at: string;
  updated_at?: EmployeeResponseUpdatedAt;
}
