/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateSlackSlotRequestClientId } from './updateSlackSlotRequestClientId';
import type { UpdateSlackSlotRequestClientSecret } from './updateSlackSlotRequestClientSecret';
import type { UpdateSlackSlotRequestAppToken } from './updateSlackSlotRequestAppToken';

export interface UpdateSlackSlotRequest {
  client_id?: UpdateSlackSlotRequestClientId;
  client_secret?: UpdateSlackSlotRequestClientSecret;
  app_token?: UpdateSlackSlotRequestAppToken;
}
